language: python
python:
- 3.8.6
matrix:
  include:
  - python: 3.8.6
cache:
- pip
- directories:
  - "$HOME/.pyenv_cache"
before_install:
- |
  if [[ -n "$PYENV_VERSION" ]]; then
    wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
    source setup-pyenv.sh
  fi
install:
- pipenv install --dev
script:
- pytest -v --cov=executor .
after_success:
- pyenv shell
- codecov
- pip install codacy-coverage
- python-codacy-coverage -r coverage.xml
- py.test --cov-report=xml --cov=gmrs tests/
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: __token__
  password:
    secure: krhron5BDWRr4fxA9bj2dPteE+FCtiRcVKSj66ZN+PJFfjSJxfwuKwVHJbjzvoUd1EZ3uUAFIMIWzgObUh9R0kgKFruM7QTyer2vLiUiIFGaiLv4UO3/M19xLr0qKWSl5jEl7WXJUq7g37vue62juEBqFyr3E0zBD39O1XEltDmYE+LGWR2WThxYbdhnZDwz/MM8IOsU1V4wSKfkBRAyh4zUP/KdyvudjmaEIly7XaZ47EBgmdZp3IVkQrzNbpdx+3Gs0WVcQzG3PPueNpW6PptBWO4+4HwKwfIXvgO1fWbZpjI+l2q8bHtWsLH85SyC7cG258n4pzJTZ7k0NELNer7qbQzLeo0E/nHGuyA8596/8LaiVPNTuxDyF0FJoggYtE5ayO0b52/vyOc6jTW/3sa3Z5ac6Lv20XAE+TthaQpf1MiJ2tobbgyf7yaUHqKHGLmaQksYWlFtdhodj4kbc+Ox6sE1H99eO9nkc1cThJBwyQewntNFj5607YBrV66jfOf+h+OGoLvvE3GuN4n/zZA/vz0oEpvjAqLC26Fr6HyIWJbtJ1JfC0n25m3/OoMx11Wo9YnDzCaBV5TM2KOJvAUV1UH2FfXoh2lqToDAYAivJ/WLOWipVDjYpIkSKtujuqZ07rZ0ZApCBaONDWIObMOyeFYrFeqWTQUkykVINGE=
  on:
    all_branches: true
    tags: true
